# Generated by Django 2.1 on 2019-10-10 10:17

import blog.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_month='pub_date')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('post_title_picture', models.ImageField(blank=True, upload_to=blog.models.post_title_directory_path)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='date modified')),
                ('authors', models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blog post',
                'ordering': ['-pub_date', 'title'],
                'permissions': (('view_future_post', 'Can view unplished Post'),),
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.Tag'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together={('slug', 'pub_date')},
        ),
    ]
